export type Application = {
    id: number;
    isComplete: boolean;
    firstname: string | null;
    lastname: string | null;
    dob: number | null;
    street: string | null;
    city: string | null;
    state: string | null;
    zip: number | null;
    vehiclevin1: string | null;
    vehicleyear1: number | null;
    vehiclemake1: string | null;
    vehiclevin2?: string | null;
    vehicleyear2?: number | null;
    vehiclemake2?: string | null;
    vehiclevin3?: string | null;
    vehicleyear3?: number | null;
    vehiclemake3?: string | null;
    price?: number | null;
};
